import { model, Schema } from 'mongoose'
import { ICountriesDocument } from '../types/documents/country.document'

const countriesSchema = new Schema(
  {
    deleted: Boolean,
    fundVisaChecklist: [],
    flagImage: [
      {
        _id: Schema.Types.ObjectId,
        name: String,
        path: String,
        url: String,
        uid: String,
      },
    ],
    mapImage: String,
    mediaFiles: [
      {
        _id: Schema.Types.ObjectId,
        name: String,
        path: String,
        url: String,
        uid: String,
      },
    ],
    id: String,
    countryCode: String,
    countryName: String,
    currencyName: String,
    currencyRate: Number,
    uid: String,
    time: Date,
    complete: Number,
    enrollmentBasic: String,
    enrollmentProcedure: String,
    enrollmentRemarks: String,
    airTicketPrice: Number,
    airTicketType: String,
    child1PermitFee: Number,
    child1Vfs: Number,
    child2PermitFee: Number,
    child2Vfs: Number,
    child3PermitFee: Number,
    child3Vfs: Number,
    child4PermitFee: Number,
    childrenAboveAge: Number,
    familyEstimatedCost: Number,
    livingCostChild1: Number,
    livingCostChild2: Number,
    livingCostMainApplicant: Number,
    livingCostSpouse: Number,
    mainApplicantPermitFee: Number,
    mainApplicantVfs: Number,
    singleEstimatedCost: Number,
    spousePermitFee: Number,
    spouseVfs: Number,
    stageApplication: Number,
    stageVisaApproval: Number,
    stageVisaFilling: Number,
    travelCostChild: Number,
    travelCostMainApplicant: Number,
    travelCostSpouse: Number,
    visaFeeChild1: Number,
    visaFeeChild3: Number,
    visaFeeChild4: Number,
    visaFeeMainApplicant: Number,
    visaFeeSpouse: Number,
    fundAcceptable: String,
    fundEducation: String,
    fundRefundable: String,
    fundSponsors: String,
    AHM: String,
    NIB: String,
    allainze: String,
    buppa: String,
    dualOSHC: Number,
    embassyAddress: String,
    embassyContacts: String,
    embassyEmail: String,
    familyOSHC: Number,
    interview: String,
    interviewType: String,
    mainCities: String,
    mainStates: String,
    mediBank: String,
    singleOSHC: Number,
    tutionFeeReq: String,
    vfsttsAddress: String,
    vfsttsContacts: String,
    vfsttsEmail: String,
    videoUrl: String,
    visaCategory: String,
    visaFillingBy: String,
    visaProcessingTime: String,
    createdByUser: {
      _id: Schema.Types.ObjectId,
      name: String,
      userId: String,
      time: Date,
    },
    updatedByUser: {
      _id: Schema.Types.ObjectId,
      name: String,
      userId: String,
      time: Date,
    },
    totalConsultancyFee: Number,
    totalPermitFee: Number,
    totalVfsFee: Number,
  },
  { timestamps: true }
)

export const CountryModel = model<ICountriesDocument>('countrie', countriesSchema)
